//
//  UIColor+BCAdditions.swift
//
//  Generated by Zeplin on 10/16/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var bcAzure: UIColor {
		return UIColor(red: 33.0 / 255.0, green: 150.0 / 255.0, blue: 243.0 / 255.0, alpha: 1.0)
	}
}
